server {
  listen 80;
  listen [::]:80;
  server_name hub.engenize.com.br;
  if ($host != hub.engenize.com.br) { return 444; }

  location /.well-known/acme-challenge/ {
    root /var/www/letsencrypt;
  }
  location / { return 503; }
}

server {
  listen 443;
  listen [::]:443;
  server_name hub.engenize.com.br;
  ssl_reject_handshake on;
}
