ALTER TABLE demanda DROP CONSTRAINT demanda_status_check;
ALTER TABLE demanda ADD CONSTRAINT demanda_status_check CHECK (status IN (
  'AGUARDANDO_DESENVOLVIMENTO', 'EM_DESENVOLVIMENTO',
  'DESENVOLVIMENTO_EM_PROGRESSO', 'EM_TESTE', 'REABERTA', 'ENCERRADA'
));
ALTER TABLE demanda ADD COLUMN encerrada_em TIMESTAMPTZ;
